Http/routes.php
<?php

  Route::group(['middleware'=> ['auth', config('codeeduuser.middleware.isVerified')]], function() {

	Route::resource('categories', 'CategoriesController', ['except' => 'show']);

	Route::resource('books', 'BooksController', ['except' => 'show']);

	Route::group(['prefix' => 'trashed', 'as' => 'trashed.'], function(){

		Route::resource('books', 'BooksTrashedController', 
			['except' => 'create', 'store', 'edit', 'destroy']);
	});

});

Models/Book.php
<?php

namespace CodeEduBook\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;
use Bootstrapper\Interfaces\TableInterface;
use Collective\Html\Eloquent\FormAccessible;
use Illuminate\Database\Eloquent\SoftDeletes;

class Book extends Model implements TableInterface
{
    use FormAccessible;

    use SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $fillable = [
    	'title',
    	'subtitle',
    	'price',
        'author_id'
    ];

    public function author()
    {
    	// Relacionamento de muitos para um
    	return $this->belongsTo(\CodeEduUser\Models\User::class);
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class)->withTrashed();
    }

    public function formCategoriesAttribute()
    {
        return $this->categories->pluck('id')->all();
    }

    public function getTableHeaders()
    {
    	return ['#', 'Titulo', 'Autor', 'Preço'];
    }

    public function getValueForHeader($header)
    {
    	switch ($header) {
    		case '#':
    			return $this->id;
    		
    		case 'Titulo':
    			return $this->title;

    		case 'Autor':
    			return $this->author->name;	

    		case 'Preço':
    			return $this->price;	
    		
    	}
    }



}

Http/Controllers/BooksController.php
<?php

namespace CodeEduBook\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
//use Illuminate\Routing\Controller;
use CodeEduBook\Http\Requests\BookCreateRequest;
use CodeEduBook\Http\Requests\BookUpdateRequest;
use CodeEduBook\Repositories\BookRepository;
use CodeEduBook\Repositories\CategoryRepository;
use CodeEduBook\Models\Book;
use CodeEduBook\Models\Category;
use CodePub\Criteria\FindByTitleCriteria;
use CodePub\Criteria\FindByAuthorCriteria;

class BooksController extends Controller
{
    /**
     * @var BookRepository
     */
    protected $repository;

    protected $categoryRepository;

    public function __construct(BookRepository $repository, CategoryRepository $categoryRepository)
    {
        $this->repository = $repository;

        $this->categoryRepository = $categoryRepository;
    }

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $books = $this->repository->paginate(10);

        return view('codeedubook::books.index', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        $categories = $this->categoryRepository->lists('name', 'id'); //pluck

        return view('codeedubook::books.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function store(BookCreateRequest $request)
    {
        $data = $request->all();

        $data['author_id'] = \Auth::user()->id;

        $this->repository->create($data);
        // pegando a url anterior da requisição para redirecionar para a mesma    
        $url = $request->get('redirect_to', route('books.index'));
        // criando mensagens    
        $request->session()->flash('message', 'Livro cadastrado com sucesso!');

        return redirect()->to($url);
    }

    /**
     * Show the form for editing the specified resource.
     * @return Response
     */
    public function edit($id)
    {
        $book = $this->repository->find($id);

        $this->categoryRepository->withTrashed();

        $categories = $this->categoryRepository->listsWithMutators('name_trashed', 'id');

        return view('codeedubook::books.edit', compact('book', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function update(BookUpdateRequest $request, $id)
    {
        // retorna todos os dados exceto oque colocar nos parametros
        $data = $request->except(['author_id']);

        $this->repository->update($request->all(), $id);
        // pegando a url anterior da requisição para redirecionar para a mesma
        $url = $request->get('redirect_to', route('books.index'));

        $request->session()->flash('message', 'Livro alterado com sucesso!');

        return redirect()->to($url);
    }

    /**
     * Remove the specified resource from storage.
     * @return Response
     */
    public function destroy($id)
    {
        $this->repository->delete($id);

        \Session::flash('message', 'Livro excluído com sucesso!');
        
        return redirect()->to(\URL::previous());
    }
}

resources/views/trashed/books/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<h1>Lixeira de Livros</h1><br>
			</div>
		</div>
		<div class="row">
			{!! Form::model([], ['class' => 'form', 'method' => 'GET']) !!}
				<div class="form-group col-md-6">
					{!! Form::label('search', 'Pesquisar por título ou autor:', ['class'=>'control-label']) !!}
					{!! Form::text('search', null, ['class' => 'form-control']) !!}
				</div>
				<div class="form-group col-md-2">
					<br>{!! Button::primary('Buscar')->submit() !!}
				</div>
			{!! Form::close() !!}
		</div>
		<hr>
		<div class="row">
			<div class="col-md-12">
				<!-- FORMA MAIS PRÁTICA DE FAZER TABELA USANDO O BOOTSTRAPPER -->
				@if($books->count() > 0)
				{!! 
					Table::withContents($books->items())->striped()
						->callback('Ações', function($field, $book){
							$linkView = route('trashed.books.show', ['book' => $book->id]);
							$linkDestroy = route('books.destroy', ['book' => $book->id]);
							$restoreForm = "restore-form-{$book->id}";
							$form = Form::open(['route' =>
										['trashed.books.update', 'book' => $book->id],
										'method' => 'PUT', 'id' => $restoreForm, 'style' => 'display:none']).
										Form::hidden('redirect_to', URL::previous()).
										Form::close();
							$anchorRestore = Button::danger('Restaurar')->asLinkTo($linkDestroy)->addAttributes([
												'onclick' => "event.preventDefault();document.getElementById(\"{$restoreForm}\").submit();"
											]);			
							return "<ul class=\"list-inline\">".
										"<li>".Button::primary('Visualizar')->asLinkTo($linkView)."</li>".
										"<li>|</li>".
										"<li>".$anchorRestore."</li>".
									"</ul>".
									$form;
					})
				!!}
				@else
				<br>
				<div class="well well-lg text-center">
					<strong>A lixeira está vazia</strong>
				</div>
				@endif
			</div>
		</div>
		<div class="col-md-offset-4 col-md-4">
			{{$books->links()}}
		</div>
	</div>
@endsection

resources/views/trashed/books/show.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<h3>Livro - {{$book->title}}</h3>
			<ul class="list-group">
				<li class="list-group-item"><strong>Título</strong></li>
				<li class="list-group-item">{{$book->title}}</li>
				<li class="list-group-item">{{ $book->subtitle}}</li>
				<li class="list-group-item"><strong>Preço</strong></li>
				<li class="list-group-item">{{ $book->price}}</li>
				<li class="list-group-item"><strong>Categoria</strong></li>
				<li class="list-group-item">{{ $book->categories->implode('name_trashed', ', ')}}</li>
			</ul>
		</div>
		<div class="row">
			{!! Button::primary('Voltar para Lixeira')->asLinkTo(route('trashed.books.index')) !!}
		</div>
	</div>
@endsection